packages:
  - '**'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@swc/core': false
  cypress: false
  esbuild: false
  prisma: false
  sharp: false
ignoredBuiltDependencies:
  - cypress
  - esbuild
  - sharp
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
